name: expense_manger
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  percent_indicator: ^4.2.2

  # State Management & Storage
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.1

  pie_chart: ^5.3.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
